import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  const [email, setEmails] = useState(props.myEmails)
  const emailCounter = email.length
  return (
    <>
    <style jsx>
      {`
      .emails{
        width: 100%;
    border-radius: 10px;
    display: flex;
    justify-content: center;
    margin-bottom:30px;
    background-color: rgba(255, 255, 255, 0.2); /* Semi-transparent white background */
    backdrop-filter: blur(10px);
    box-shadow: 5px 10px 20px 0px rgba(0, 0, 0, 0.5);
      }

      .emails p{
        font-size: 20px;
        background-color: rgba(255, 50, 255, 0.1); /* Semi-transparent white background */
    backdrop-filter: blur(10px);
      }

      .EmailContainers h3{
        font-size: 30px;
        text-align: center;
      }
      `}
    </style>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="EmailContainers">
        <h3>Number of Emails in Database: {emailCounter}</h3>
        {email.map((item)=>{
          return <div className="emails" key={item.email}>
            <p>{item.email}</p>
          </div>
        })}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const data = await fetch('http://localhost:3000/api/getemails');
  var myEmails = await data.json();
 
  // Pass data to the page via props
  return { props: { myEmails } }
}
